name: Extract Library Version

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      library-version:
        description: The extracted library version
        value: ${{ jobs.extract-version.outputs.library-version }}

jobs:
  extract-version:
    name: Extract Library Version

    runs-on: ubuntu-latest

    permissions:
      contents: read

    # Map the job outputs to step outputs
    outputs:
      library-version: ${{ steps.extract.outputs.library-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Extract Kache version
        id: extract
        run: |
          echo "library-version=$(sed -rn 's/^VERSION_NAME=(.*)\r?$/\1/p' 'gradle.properties')" >> $GITHUB_OUTPUT
